### ISSUE TITLE
Importing file with more that 494 lines

### ISSUE THREAD

**Issue by bhaskarvyas001** [bahaaldine/angular-csv-import#29] opened 2015-10-06 04:03 UTC
Hi,

I have a CSV with 14 columns and over 900 rows.
When I try to upload it, I can see that the plugin reads only 494 row and ignore the rest.
Can you please confirm if tehre is a limit on the data that can be read and uploaded in one go.?

regards,
Deepak

**Comment by bahaaldine** [comment] 2015-11-26 09:22
Duplicate of #20

**Closed by bahaaldine** 2015-11-26 09:22 UTC
